### ISSUE TITLE
float32

### ISSUE THREAD

**Issue by le000043** [sayakpaul/Denoised-Smoothing-TF#1]
Hello, thank you for implementing this great application. However, for your train_denoiser.ipynb, I ran it on my Google Colab and it gave me a mismatched type of float32. If I change all float32 types to float64, it fixes the error. This can be something to keep in mind in the next update of your code.

**Comment by sayakpaul** [comment]
Thanks for reporting this. However, I did not find any such errors when I ran it. Could you share a notebook that has the errors?

**Comment by le000043** [comment]
https://colab.research.google.com/drive/1dTiQridJDCLdK6D4wIMe0PWm4U-MGaLN?usp=sharing
this happens to the train_classifier also

**Comment by sayakpaul** [comment]
Sure. Will check and get back.

**Comment by sayakpaul** [comment]
This is likely because of the TensorFlow version mismatch. I used TensorFlow 2.4.1. Besides if you change the dtype of the noise to `float32` it should not happen. 

```python
noise = tf.experimental.numpy.random.randn(batch_size, 32, 32, 3) * self.sigma
noise = tf.cast(noise, tf.float32)
```

I have made a note about it in the [README](https://github.com/sayakpaul/Denoised-Smoothing-TF/blob/main/README.md#further-notes).
